database:
  url: "mongodb://localhost:27017"
  dbname: "handyhub"
  email-collection: "emails"
  timeout: 10

storage:
  type: database
  file:
    path: "logs/emails"
    max-size: 10
    max-files: 5

redis:
  url: "localhost:6379"
  password: ""
  db: 3

queue:
  rabbitmq:
    url: "amqp://guest:guest@localhost:5672/"
    exchange: "handyhub"
    exchange-type: "topic"
    email-queue: "email_queue"
    prefetch-count: 1
    prefetch-size: 0
    global: false
    reconnect-delay: 5
    timeout: 10
    routing-key: "email.send"
    durable: true
    auto-delete: false
    internal: false
    no-wait: false
    exclusive: false
    auto-ack: false
    no-local: false
    consumer: "email_consumer"

server:
  port: ":8008"
  read-timeout: 30
  write-timeout: 30
  idle-timeout: 60

app:
  name: "handyhub-email-svc"
  timeout: 30

logs:
  level: "info"
  log-path: "logs/sys.log"
  #log-path: "../../../logs/sys.log"

email:
  smtp-host: "localhost"
  smtp-port: 1025
  smtp-user: ""
  smtp-password: ""
  from-email: "noreply@handyhub.com"
  from-name: "HandyHub"

smtp:
  provider: mailhog
  default-from: "noreply@handyhub.com"
  mailhog:
    host: "localhost"
    port: 1025