database:
  url: "mongodb://localhost:27017"
  dbname: "handyhub"
  email-collection: "emails"
  timeout: 10

storage:
  type: console
  file:
    path: "emails"
    max-size: 10
    max-files: 5

redis:
  url: "localhost:6379"
  password: ""
  db: 3

server:
  port: ":8008"
  read-timeout: 30
  write-timeout: 30
  idle-timeout: 60

app:
  name: "handyhub-email-svc"
  timeout: 30

logs:
  level: "info"
  log-path: "logs/sys.log"
  #log-path: "../../../logs/sys.log"

email:
  smtp-host: "localhost"
  smtp-port: 1025
  smtp-user: ""
  smtp-password: ""
  from-email: "noreply@handyhub.com"
  from-name: "HandyHub"